import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: 70,
  slug: "data-engineer",
  title: "Data Engineer",
  department: "Data",
  team: "Data",
  location: "Remote (Global)",
  type: "Full-time / Part-time",
  techStack: [
    "Python",
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Kafka",
    "AWS / GCP",
    "ETL / ELT",
  ],
  successLooksLike: [
    "Reliable and scalable data pipelines in production",
    "High-quality and accessible data across teams",
    "Efficient reporting and analytics infrastructure",
    "Optimized data processing and storage systems",
    "Strong collaboration between engineering and business teams",
  ],
  hiringProcess: [
    "Application review",
    "Technical screening (SQL and data engineering discussion)",
    "Practical exercise or architecture review",
    "Final discussion",
  ],
  howToApply: [
    "Resume or LinkedIn",
    "GitHub profile or project portfolio (preferred)",
    "Examples of data pipelines, platforms, or engineering projects",
  ],
  sourceUrl: "https://rwa-jd.notion.site/Data-Engineer-37503938ce4280b0aba7c8ae0015e284",
  summary: "Design scalable data pipelines and analytics infrastructure.",
  about: "We are hiring a Data Engineer to design, build, and maintain scalable data pipelines and analytics infrastructure. You will work closely with product, engineering, and business teams to ensure reliable data collection, processing, storage, and reporting across multiple products and systems. This is a hands-on engineering role focused on data architecture, ETL pipelines, and analytics infrastructure.",
  responsibilities: [
    "Design and build scalable data pipelines and ETL workflows",
    "Integrate data from multiple sources and services",
    "Develop and maintain data storage and processing systems",
    "Ensure data quality, consistency, and reliability",
    "Optimize data workflows for performance and scalability",
    "Support reporting, analytics, and business intelligence initiatives",
    "Collaborate with backend, product, and analytics teams",
    "Monitor and troubleshoot data infrastructure issues",
    "Document data models, pipelines, and architecture decisions",
  ],
  requirements: [
    "3+ years of experience in data engineering",
    "Strong SQL and database design skills",
    "Experience building ETL/ELT pipelines",
    "Experience with Python or similar scripting languages",
    "Understanding of data modeling and data warehousing concepts",
    "Experience working with large datasets and distributed systems",
    "Strong problem-solving and analytical skills",
  ],
  niceToHave: [
    "Experience with cloud platforms (AWS, GCP, Azure)",
    "Familiarity with Kafka, streaming systems, or event-driven architectures",
    "Experience with PostgreSQL, MongoDB, Redis, or data warehouses",
    "Knowledge of analytics and BI platforms",
    "Experience with blockchain or Web3 data sources",
    "Exposure to machine learning data pipelines",
  ],
});
