import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: 44,
  slug: "frontend-engineer",
  title: "Frontend Engineer",
  department: "Engineering",
  team: "Delivery",
  location: "Remote (Global)",
  type: "Full-time / Part-time",
  techStack: [
    "React",
    "Next.js",
    "TypeScript",
    "TailwindCSS",
    "ethers.js",
    "PostgreSQL / backend APIs",
    "Docker",
    "AWS / GCP",
  ],
  successLooksLike: [
    "Fast, responsive, and stable web applications",
    "Clean and reusable UI component architecture",
    "Smooth integration with backend and blockchain systems",
    "High-quality user experience across all devices",
    "Strong collaboration with design and engineering teams",
  ],
  hiringProcess: [
    "Application review",
    "Technical interview (React + system design basics)",
    "Final discussion",
  ],
  howToApply: [
    "Resume or LinkedIn",
    "GitHub profile (required)",
    "Examples of frontend or Web3 UI projects",
  ],
  sourceUrl: "https://rwa-jd.notion.site/Frontend-Engineer-35303938ce4280559e01d992cf36ee6e",
  summary: "Build modern, responsive web apps for blockchain and digital products.",
  about: "We are hiring a Frontend Engineer to build modern, responsive, and high-performance web applications. You will be responsible for developing user interfaces for blockchain and digital products, working closely with backend, product, and design teams to deliver seamless user experiences. This is a hands-on engineering role focused on product quality, performance, and usability.",
  responsibilities: [
    "Build and maintain web applications using React and Next.js",
    "Develop responsive, high-performance UI components",
    "Integrate frontend applications with backend APIs and blockchain services",
    "Implement wallet connections and Web3 interactions (where applicable)",
    "Work closely with designers to implement UI/UX accurately",
    "Optimize applications for speed, scalability, and performance",
    "Ensure code quality through testing and best practices",
    "Participate in code reviews and technical discussions",
  ],
  requirements: [
    "3+ years of frontend development experience",
    "Strong proficiency in React and Next.js",
    "Solid understanding of TypeScript",
    "Experience working with REST APIs and/or GraphQL",
    "Good understanding of responsive design and UI best practices",
    "Experience with Git and modern frontend workflows",
    "Ability to collaborate with backend and design teams",
  ],
  niceToHave: [
    "Experience with Web3 integrations (ethers.js, wallet connections)",
    "Familiarity with blockchain UI patterns (DeFi, dashboards, transactions)",
    "Experience with performance optimization techniques",
    "Knowledge of design systems or component libraries",
    "Basic backend understanding (Node.js)",
  ],
});
