import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: 60,
  slug: "product-manager",
  title: "Product Manager",
  department: "Product",
  team: "Product",
  location: "Remote (Global)",
  type: "Full-time / Part-time",
  techStack: [
    "Blockchain applications",
    "Web applications",
    "Mobile applications",
    "Backend systems (Node.js, Go, Rust)",
    "Cloud infrastructure",
  ],
  successLooksLike: [
    "Clear and well-defined product requirements",
    "On-time and high-quality project delivery",
    "Strong alignment between clients and engineering teams",
    "Reduced ambiguity and improved execution efficiency",
    "Successful feature releases and product iterations",
  ],
  hiringProcess: [
    "Application review",
    "Product thinking interview (case discussion)",
    "Technical collaboration / scenario exercise",
    "Final discussion",
  ],
  howToApply: [
    "Resume or LinkedIn",
    "Examples of products or projects managed",
    "Brief description of delivery challenges handled",
  ],
  sourceUrl: "https://rwa-jd.notion.site/Product-Manager-35303938ce42819189f6e4c0b7dbabd3",
  summary: "Lead product planning and delivery across software development projects.",
  about: "We are hiring a Product Manager to lead product planning, execution, and delivery across software development projects. You will act as the bridge between clients, business stakeholders, and engineering teams, ensuring clear requirements, strong execution, and successful product delivery. This role is both strategic and execution-focused, with direct involvement in product lifecycle management.",
  responsibilities: [
    "Define product requirements based on client and business needs",
    "Translate business goals into clear technical specifications",
    "Work closely with engineering teams (backend, frontend, blockchain, QA)",
    "Manage product roadmap, scope, and delivery timelines",
    "Write user stories, acceptance criteria, and PRDs",
    "Prioritize features based on value, risk, and effort",
    "Coordinate with designers and business analysts",
    "Ensure successful product delivery across development cycles",
    "Gather feedback and iterate on product improvements",
  ],
  requirements: [
    "3+ years of experience in product management or delivery roles",
    "Experience working with software development teams",
    "Strong understanding of Agile / Scrum methodologies",
    "Ability to communicate with technical and non-technical stakeholders",
    "Experience writing product requirements and user stories",
    "Strong organizational and prioritization skills",
    "Ability to manage multiple projects simultaneously",
  ],
  niceToHave: [
    "Experience in outsourcing or agency environments",
    "Familiarity with blockchain, fintech, or enterprise software",
    "Technical background (engineering, QA, or business analysis)",
    "Experience with tools like Jira, Confluence, Notion, or Linear",
    "UX/UI understanding or experience working with design teams",
  ],
});
