import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: 64,
  slug: "product-designer",
  title: "Product Designer",
  department: "Design",
  team: "Design",
  location: "Remote (Global)",
  type: "Full-time / Part-time",
  techStack: [
    "Figma",
    "React · Next.js context",
    "Design systems",
    "Web3 wallet UX patterns",
  ],
  successLooksLike: [
    "Clear, intuitive user experiences across all products",
    "Reduced user friction in blockchain interactions",
    "Strong, consistent design system across applications",
    "Improved usability and onboarding conversion",
    "High-quality collaboration with engineering teams",
  ],
  hiringProcess: [
    "Application review",
    "Portfolio review (critical step)",
    "Design task (UX problem-solving exercise)",
    "Final discussion",
  ],
  howToApply: [
    "Resume or LinkedIn",
    "Portfolio (required)",
    "Case studies or product design examples",
  ],
  sourceUrl: "https://rwa-jd.notion.site/Product-Designer-UI-UX-Web3-Digital-Products-35303938ce4280af91d0effea3854543",
  summary: "Design intuitive interfaces for blockchain and digital products.",
  about: "We are hiring a Product Designer to design intuitive, user-centered interfaces for blockchain and digital products. You will be responsible for turning complex technical systems into simple, usable, and visually clear experiences across web and mobile applications. This is a hands-on design role with strong product involvement, working closely with engineering and product teams.",
  responsibilities: [
    "Design user interfaces for web and mobile applications",
    "Create user flows, wireframes, and high-fidelity mockups",
    "Work closely with product managers and engineers to define UX requirements",
    "Simplify complex blockchain interactions into usable experiences",
    "Design onboarding flows, dashboards, and transactional interfaces",
    "Maintain and evolve design systems and UI components",
    "Conduct UX thinking around usability, clarity, and accessibility",
    "Collaborate with frontend developers during implementation",
    "Iterate designs based on user feedback and product needs",
  ],
  requirements: [
    "3+ years of experience in product or UX/UI design",
    "Strong portfolio of web or mobile product design work",
    "Experience designing complex systems or data-heavy interfaces",
    "Proficiency in Figma (or similar design tools)",
    "Strong understanding of UX principles and interaction design",
    "Ability to work closely with engineering teams",
    "Good communication and problem-solving skills",
  ],
  niceToHave: [
    "Experience in Web3 / blockchain / fintech products",
    "Understanding of wallet flows, transactions, or DeFi UX",
    "Experience designing design systems at scale",
    "Basic understanding of frontend development (HTML/CSS/React)",
    "Experience in startup or fast-paced environments",
    "Motion design or prototyping skills",
  ],
});
