import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: 16,
  slug: "tech-lead",
  title: "Tech Lead",
  department: "Engineering",
  team: "Platform",
  location: "Remote (Global)",
  type: "Full-time / Part-time",
  techStack: [
    "Node.js",
    "TypeScript",
    "PostgreSQL",
    "Redis",
    "ethers.js",
    "Docker",
    "Kubernetes",
    "AWS / GCP",
  ],
  successLooksLike: [
    "Stable and scalable backend systems in production",
    "Clear and consistent architecture across services",
    "Reduced production issues and improved system reliability",
    "Strong engineering culture and code quality",
    "Efficient collaboration between backend and blockchain teams",
  ],
  hiringProcess: [
    "Application review",
    "Technical discussion (system design + backend architecture)",
    "Leadership interview (technical + team execution)",
    "Final discussion",
  ],
  howToApply: [
    "Resume or LinkedIn",
    "GitHub profile (required)",
    "Examples of backend systems or architecture work",
  ],
  sourceUrl: "https://rwa-jd.notion.site/Tech-Lead-35303938ce4281a1a509d1fdcd9717b1",
  summary: "Lead architecture and engineering execution across backend and blockchain-integrated systems.",
  about: "We are hiring a Tech Lead to lead architecture, engineering execution, and technical direction across backend and blockchain-integrated systems. You will be responsible for ensuring scalable, secure, and production-ready backend systems, while guiding a team of engineers and maintaining high engineering standards. This is a hands-on leadership role (you still code).",
  responsibilities: [
    "Lead backend architecture and system design decisions",
    "Oversee development of Node.js/TypeScript backend services",
    "Guide integration with blockchain smart contracts and APIs",
    "Review code and enforce engineering best practices",
    "Design scalable APIs, services, and data models",
    "Coordinate backend development across multiple projects",
    "Work closely with blockchain engineers and frontend teams",
    "Define technical standards (testing, CI/CD, architecture patterns)",
    "Mentor engineers and improve team execution quality",
    "Participate in hiring and technical interviews",
  ],
  requirements: [
    "5+ years of backend engineering experience",
    "Strong expertise in Node.js and TypeScript",
    "Proven experience leading technical teams or projects",
    "Strong system design and architecture skills",
    "Experience with PostgreSQL, Redis, and scalable backend systems",
    "Understanding of REST APIs and/or GraphQL",
    "Experience integrating external systems (APIs, Web3, or microservices)",
    "Strong coding fundamentals and ability to review production code",
  ],
  niceToHave: [
    "Experience with blockchain or Web3 integrations (ethers.js, smart contract APIs)",
    "Experience in distributed systems or event-driven architectures",
    "Familiarity with cloud infrastructure (AWS / GCP)",
    "Experience in fintech, SaaS, or consulting environments",
    "Exposure to high-scale backend systems",
  ],
});
