/**
 * One-shot generator: Notion-aligned JDs → src/content/jobs/roles/*.ts
 * Run: node scripts/generate-jds.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rolesDir = path.join(__dirname, "../src/content/jobs/roles");

const LOC = "Remote (Global)";
const TYPE = "Full-time / Part-time";

/** @type {Array<Record<string, unknown>>} */
const jobs = [
  {
    file: "mobile-developer.ts",
    order: 10,
    slug: "mobile-developer",
    title: "Mobile Developer",
    department: "Engineering",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Mobile-Developer-39903938ce4280a6806dc9a431ef22dc",
    summary: "Build high-quality iOS and Android apps for blockchain and digital products.",
    about:
      "We are hiring a Mobile Developer to build modern, performant mobile applications. You will own mobile UI, API integration, and release quality for products used by operators and end users. This is a hands-on engineering role focused on product quality, performance, and usability.",
    responsibilities: [
      "Build and maintain iOS and/or Android applications",
      "Implement responsive, high-performance mobile UI",
      "Integrate mobile apps with backend APIs and blockchain services",
      "Implement wallet and Web3 flows where applicable",
      "Collaborate with designers to ship accurate UX",
      "Optimize apps for performance, stability, and store readiness",
      "Write tests and participate in code reviews",
    ],
    requirements: [
      "3+ years of mobile development experience",
      "Strong proficiency in React Native, Flutter, Swift, or Kotlin",
      "Solid understanding of mobile architecture and state management",
      "Experience with REST APIs and authentication flows",
      "Familiarity with App Store / Play Store release processes",
      "Ability to collaborate with backend and design teams",
    ],
    niceToHave: [
      "Experience with Web3 mobile wallets or dApp browsers",
      "Push notifications, deep linking, and offline-first patterns",
      "CI/CD for mobile (Fastlane, EAS, Bitrise)",
      "Basic backend understanding",
    ],
    techStack: ["React Native / Flutter", "TypeScript", "iOS · Android", "REST APIs", "Wallet SDKs"],
    successLooksLike: [
      "Stable, performant mobile releases",
      "Clean reusable mobile architecture",
      "Smooth API and blockchain integrations",
      "High-quality UX across devices",
    ],
    hiringProcess: [
      "Application review",
      "Technical interview (mobile + architecture)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "GitHub profile (required)",
      "Examples of mobile apps shipped",
    ],
  },
  {
    file: "backend-engineer.ts",
    order: 20,
    slug: "backend-engineer",
    title: "Backend Engineer",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Backend-Engineer-35303938ce4281e3a102d0e9c33b5280",
    summary: "Design and ship scalable Node.js/TypeScript services for Web3 and digital products.",
    about:
      "We are hiring a Backend Engineer to design, build, and maintain scalable backend services. You will own APIs, data models, and integrations with blockchain and third-party systems. This is a hands-on engineering role focused on reliability, security, and production readiness.",
    responsibilities: [
      "Build and maintain backend services with Node.js and TypeScript",
      "Design REST and/or GraphQL APIs",
      "Model data and own PostgreSQL / Redis usage",
      "Integrate blockchain APIs, wallets, and external services",
      "Implement auth, permissions, and operational controls",
      "Write tests, improve observability, and participate in reviews",
      "Ship production-ready services with CI/CD",
    ],
    requirements: [
      "3+ years of backend engineering experience",
      "Strong proficiency in Node.js and TypeScript",
      "Experience with PostgreSQL and Redis",
      "Solid understanding of REST APIs and system design basics",
      "Experience integrating external APIs or microservices",
      "Strong coding fundamentals and production debugging skills",
    ],
    niceToHave: [
      "Web3 integrations (ethers.js, smart contract APIs)",
      "Event-driven or distributed systems experience",
      "AWS / GCP familiarity",
      "Fintech or consulting experience",
    ],
    techStack: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "ethers.js", "Docker", "AWS / GCP"],
    successLooksLike: [
      "Stable APIs in production",
      "Clear data models and service boundaries",
      "Reliable integrations with blockchain systems",
      "Low operational noise and strong code quality",
    ],
    hiringProcess: [
      "Application review",
      "Technical discussion (backend + system design)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "GitHub profile (required)",
      "Examples of backend systems shipped",
    ],
  },
  {
    file: "go-backend-engineer.ts",
    order: 22,
    slug: "go-backend-engineer",
    title: "Go Backend Engineer",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Go-Backend-Engineer-37703938ce4280819afddcf74120da66",
    summary: "Build high-performance Go services for APIs, workers, and blockchain-adjacent systems.",
    about:
      "We are hiring a Go Backend Engineer to build high-performance backend services. You will own services, workers, and data paths that must stay fast and reliable under load. This is a hands-on role focused on concurrency, correctness, and production operations.",
    responsibilities: [
      "Design and implement Go microservices and APIs",
      "Build background workers, queues, and scheduled jobs",
      "Optimize performance, memory use, and concurrency",
      "Integrate databases, caches, and external systems",
      "Improve observability, testing, and deployment pipelines",
      "Collaborate with product and blockchain engineers",
    ],
    requirements: [
      "3+ years of backend experience with strong Go proficiency",
      "Experience building production Go services",
      "Solid SQL and data modeling skills",
      "Understanding of concurrency patterns and performance tuning",
      "Experience with REST APIs and service-oriented architectures",
      "Comfort with Git, testing, and CI/CD",
    ],
    niceToHave: [
      "gRPC, Kafka, or event-driven systems",
      "Kubernetes and cloud infrastructure",
      "Blockchain node or indexer experience",
      "Fintech or high-throughput systems",
    ],
    techStack: ["Go", "PostgreSQL", "Redis", "gRPC / REST", "Docker", "Kubernetes", "AWS / GCP"],
    successLooksLike: [
      "Fast, reliable Go services in production",
      "Clear service contracts and low latency paths",
      "Strong test coverage and operational visibility",
    ],
  },
  {
    file: "rust-backend-engineer.ts",
    order: 24,
    slug: "rust-backend-engineer",
    title: "Rust Backend Engineer",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Rust-Backend-Engineer-35303938ce428146b629f168bcc26ec3",
    summary: "Build safe, high-performance Rust services for critical backend and chain-adjacent workloads.",
    about:
      "We are hiring a Rust Backend Engineer to build performance-critical backend systems. You will work on services where correctness, memory safety, and throughput matter. This is a hands-on engineering role with strong ownership of architecture and delivery.",
    responsibilities: [
      "Design and implement Rust backend services and libraries",
      "Own performance-sensitive data paths and parsers",
      "Integrate with databases, queues, and blockchain systems",
      "Write rigorous tests and maintain high code quality",
      "Collaborate on APIs consumed by product and chain teams",
      "Improve tooling, CI, and operational readiness",
    ],
    requirements: [
      "3+ years of systems or backend experience",
      "Strong proficiency in Rust for production services",
      "Experience with async Rust (Tokio or similar)",
      "Solid understanding of networking, concurrency, and data structures",
      "Comfortable with SQL and service APIs",
      "Strong debugging and ownership habits",
    ],
    niceToHave: [
      "Solana / blockchain runtime experience",
      "WASM, cryptography, or parser work",
      "Distributed systems experience",
      "Cloud deployment familiarity",
    ],
    techStack: ["Rust", "Tokio", "PostgreSQL", "Redis", "gRPC / REST", "Docker", "AWS / GCP"],
    successLooksLike: [
      "Correct, high-performance Rust services",
      "Clear APIs and safe concurrency",
      "Reliable production operations",
    ],
  },
  {
    file: "java-backend-engineer.ts",
    order: 26,
    slug: "java-backend-engineer",
    title: "Java Backend Engineer",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Java-Backend-Engineer-3ce03938ce4280d49d53d15dbc00249a",
    summary: "Build enterprise-grade Java backend services for digital and RWA platforms.",
    about:
      "We are hiring a Java Backend Engineer to design and maintain scalable Java services. You will own APIs, integrations, and data layers for products that need strong reliability and clear operational controls. This is a hands-on engineering role.",
    responsibilities: [
      "Build and maintain Java backend services and APIs",
      "Design data models and persistence layers",
      "Integrate with internal services and external providers",
      "Improve reliability, testing, and observability",
      "Collaborate with frontend, product, and blockchain teams",
      "Participate in code reviews and architecture discussions",
    ],
    requirements: [
      "3+ years of Java backend development",
      "Strong Spring Boot / modern Java experience",
      "Solid SQL and relational database skills",
      "Experience with REST APIs and service design",
      "Comfort with testing and CI/CD",
      "Ability to work across product and engineering partners",
    ],
    niceToHave: [
      "Kafka or event-driven architectures",
      "Cloud platforms (AWS / GCP)",
      "Fintech, payments, or enterprise systems",
      "Blockchain API integrations",
    ],
    techStack: ["Java", "Spring Boot", "PostgreSQL", "Redis", "REST", "Docker", "AWS / GCP"],
  },
  {
    file: "blockchain-developer.ts",
    order: 30,
    slug: "blockchain-developer",
    title: "Blockchain Developer",
    department: "Engineering",
    team: "Blockchain",
    sourceUrl: "https://rwa-jd.notion.site/Blockchain-Developer-2f803938ce42802a98b3d1ddc684afc4",
    summary: "Build smart contracts and on-chain integrations for RWA and digital asset products.",
    about:
      "We are hiring a Blockchain Developer to design and implement smart contracts and chain integrations. You will work closely with backend and product teams to ship secure, production-ready on-chain systems. This is a hands-on role focused on correctness, gas efficiency, and operational safety.",
    responsibilities: [
      "Design and implement smart contracts",
      "Integrate on-chain systems with backend and frontend services",
      "Write tests, deployment scripts, and upgrade paths",
      "Review contract security and operational risks",
      "Support indexing, events, and transaction monitoring",
      "Collaborate on token, custody, and market flows",
    ],
    requirements: [
      "3+ years of software engineering experience",
      "Strong Solidity or equivalent smart contract experience",
      "Understanding of EVM fundamentals and common patterns",
      "Experience with Hardhat / Foundry (or similar)",
      "Ability to reason about security and edge cases",
      "Comfort collaborating with backend and product teams",
    ],
    niceToHave: [
      "Audit experience or formal verification exposure",
      "L2 networks (Polygon, Arbitrum, Optimism)",
      "ethers.js / web3.js integrations",
      "RWA, DeFi, or fintech product experience",
    ],
    techStack: ["Solidity", "Hardhat / Foundry", "Ethereum · L2s", "ethers.js", "Node.js", "PostgreSQL"],
  },
  {
    file: "senior-blockchain-engineer.ts",
    order: 32,
    slug: "senior-blockchain-engineer",
    title: "Senior Blockchain Engineer",
    department: "Engineering",
    team: "Blockchain",
    sourceUrl: "https://rwa-jd.notion.site/Senior-Blockchain-Engineer-35303938ce4281dca41bda4bc918302a",
    summary: "Lead architecture and delivery of production smart contract systems.",
    about:
      "We are hiring a Senior Blockchain Engineer to lead on-chain architecture and delivery. You will own complex contract systems, review quality, and mentor engineers while still shipping code. This is a senior hands-on role with high technical ownership.",
    responsibilities: [
      "Lead smart contract architecture and implementation",
      "Define standards for testing, upgrades, and deployments",
      "Review protocol designs for security and operability",
      "Guide integrations with custody, indexing, and backend systems",
      "Mentor blockchain engineers and raise code quality",
      "Partner with product on roadmap and technical tradeoffs",
    ],
    requirements: [
      "5+ years engineering experience with deep blockchain delivery",
      "Expert Solidity and EVM system design",
      "Proven production smart contract shipments",
      "Strong security mindset and review discipline",
      "Experience leading technical decisions across teams",
      "Excellent communication with product and engineering partners",
    ],
    niceToHave: [
      "Multi-chain / L2 production experience",
      "Prior audit collaboration",
      "RWA tokenization or DeFi protocol work",
      "Rust / Solana exposure",
    ],
    techStack: ["Solidity", "Foundry / Hardhat", "Ethereum · L2s", "ethers.js", "Node.js", "AWS / GCP"],
  },
  {
    file: "smart-contract-engineer.ts",
    order: 34,
    slug: "smart-contract-engineer",
    title: "Smart Contract Engineer (Rust / Solana)",
    department: "Engineering",
    team: "Blockchain",
    sourceUrl:
      "https://rwa-jd.notion.site/Smart-Contract-Engineer-Rust-Solana-3b203938ce42801a9c47f7c63ba19aae",
    summary: "Build Solana programs and Rust-based on-chain systems for product workloads.",
    about:
      "We are hiring a Smart Contract Engineer focused on Rust and Solana. You will design, implement, and ship on-chain programs with strong testing and operational discipline. This is a hands-on role working closely with backend and product teams.",
    responsibilities: [
      "Design and implement Solana programs in Rust",
      "Build account models, instructions, and client integrations",
      "Write comprehensive tests and deployment tooling",
      "Optimize compute, rent, and transaction UX",
      "Collaborate on indexing, monitoring, and operational runbooks",
      "Participate in security reviews and incident response",
    ],
    requirements: [
      "Strong Rust proficiency",
      "Hands-on Solana program development experience",
      "Understanding of Solana runtime, accounts, and PDAs",
      "Experience shipping production on-chain code",
      "Strong testing and debugging habits",
      "Ability to work with TypeScript/JS client integrations",
    ],
    niceToHave: [
      "Anchor framework experience",
      "Prior security audits or formal review work",
      "Indexer / geyser / RPC operational experience",
      "EVM background",
    ],
    techStack: ["Rust", "Solana", "Anchor", "TypeScript clients", "RPC · Indexers"],
  },
  {
    file: "smart-contract-auditor.ts",
    order: 36,
    slug: "smart-contract-auditor",
    title: "Smart Contract Auditor",
    department: "Trust",
    team: "Trust",
    sourceUrl: "https://rwa-jd.notion.site/Smart-Contract-Auditor-35303938ce4281dabd14fc4891dd03c3",
    summary: "Review smart contracts for security, correctness, and operational risk.",
    about:
      "We are hiring a Smart Contract Auditor to assess on-chain systems for vulnerabilities and design flaws. You will review contracts, write findings, and partner with engineering to remediate risk before production. This is a specialized trust role requiring deep protocol fluency.",
    responsibilities: [
      "Audit smart contracts for security and correctness issues",
      "Produce clear findings with severity and remediation guidance",
      "Partner with engineers during design and pre-release reviews",
      "Build checklists, tooling, and reusable audit artifacts",
      "Track remediation and retest critical paths",
      "Contribute to secure-by-default engineering standards",
    ],
    requirements: [
      "Proven smart contract audit experience",
      "Deep Solidity / EVM knowledge (or Solana/Rust equivalent)",
      "Ability to explain complex vulnerabilities clearly",
      "Strong threat modeling and adversarial thinking",
      "Experience with Foundry / Hardhat and static analysis tools",
      "High attention to detail and written communication quality",
    ],
    niceToHave: [
      "Published audits or public research",
      "Formal verification exposure",
      "Bug bounty experience",
      "RWA / DeFi protocol domain knowledge",
    ],
    techStack: ["Solidity", "Foundry / Hardhat", "Slither · static analysis", "EVM tooling"],
    hiringProcess: [
      "Application review",
      "Technical review (audit case discussion)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "Audit samples or public findings (required)",
      "GitHub or research links",
    ],
  },
  {
    file: "full-stack-blockchain-engineer.ts",
    order: 38,
    slug: "full-stack-blockchain-engineer",
    title: "Full-Stack Blockchain Engineer",
    department: "Engineering",
    team: "Blockchain",
    sourceUrl:
      "https://rwa-jd.notion.site/Full-Stack-Blockchain-Engineer-35303938ce428072b0a0f6ee8443d70b",
    summary: "Ship end-to-end blockchain products across contracts, APIs, and product UI.",
    about:
      "We are hiring a Full-Stack Blockchain Engineer to build product features across smart contracts, backend services, and frontend experiences. You will own slices of delivery from chain interaction to user-facing flow. This is a hands-on role for engineers who move fluidly across the stack.",
    responsibilities: [
      "Implement smart contract and Web3 integration features",
      "Build backend APIs that coordinate on-chain and off-chain state",
      "Ship frontend flows for wallets, transactions, and dashboards",
      "Own testing across contract, API, and UI layers",
      "Collaborate with design and product on complex user journeys",
      "Improve reliability of indexing and transaction UX",
    ],
    requirements: [
      "3+ years full-stack engineering experience",
      "Hands-on smart contract or Web3 integration experience",
      "Strong TypeScript across frontend and backend",
      "Experience with React and Node.js services",
      "Understanding of wallet flows and transaction states",
      "Ability to deliver production features end-to-end",
    ],
    niceToHave: [
      "Solidity or Solana program experience",
      "Indexer / subgraph experience",
      "Design system and UX collaboration skills",
      "RWA or DeFi product background",
    ],
    techStack: ["TypeScript", "React", "Node.js", "Solidity / Web3", "PostgreSQL", "ethers.js"],
  },
  {
    file: "frontend-engineer.ts",
    order: 40,
    slug: "frontend-engineer",
    title: "Frontend Engineer",
    department: "Engineering",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Frontend-Engineer-35303938ce4280559e01d992cf36ee6e",
    summary: "Build modern, responsive web apps for blockchain and digital products.",
    about:
      "We are hiring a Frontend Engineer to build modern, responsive, and high-performance web applications. You will be responsible for developing user interfaces for blockchain and digital products, working closely with backend, product, and design teams to deliver seamless user experiences. This is a hands-on engineering role focused on product quality, performance, and usability.",
    responsibilities: [
      "Build and maintain web applications using React and Next.js",
      "Develop responsive, high-performance UI components",
      "Integrate frontend applications with backend APIs and blockchain services",
      "Implement wallet connections and Web3 interactions (where applicable)",
      "Work closely with designers to implement UI/UX accurately",
      "Optimize applications for speed, scalability, and performance",
      "Ensure code quality through testing and best practices",
      "Participate in code reviews and technical discussions",
    ],
    requirements: [
      "3+ years of frontend development experience",
      "Strong proficiency in React and Next.js",
      "Solid understanding of TypeScript",
      "Experience working with REST APIs and/or GraphQL",
      "Good understanding of responsive design and UI best practices",
      "Experience with Git and modern frontend workflows",
      "Ability to collaborate with backend and design teams",
    ],
    niceToHave: [
      "Experience with Web3 integrations (ethers.js, wallet connections)",
      "Familiarity with blockchain UI patterns (DeFi, dashboards, transactions)",
      "Experience with performance optimization techniques",
      "Knowledge of design systems or component libraries",
      "Basic backend understanding (Node.js)",
    ],
    techStack: [
      "React",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "ethers.js",
      "PostgreSQL / backend APIs",
      "Docker",
      "AWS / GCP",
    ],
    successLooksLike: [
      "Fast, responsive, and stable web applications",
      "Clean and reusable UI component architecture",
      "Smooth integration with backend and blockchain systems",
      "High-quality user experience across all devices",
      "Strong collaboration with design and engineering teams",
    ],
    hiringProcess: [
      "Application review",
      "Technical interview (React + system design basics)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "GitHub profile (required)",
      "Examples of frontend or Web3 UI projects",
    ],
  },
  {
    file: "frontend-engineer-vue.ts",
    order: 42,
    slug: "frontend-engineer-vue",
    title: "Frontend Engineer (Vue)",
    department: "Engineering",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Frontend-Engineer-Vue-3c703938ce42807bb0f4cd84f93073aa",
    summary: "Build polished Vue/Nuxt interfaces for digital and Web3 product surfaces.",
    about:
      "We are hiring a Frontend Engineer (Vue) to build modern web applications with Vue and Nuxt. You will own UI quality, performance, and integrations with backend and blockchain services. This is a hands-on role focused on product experience and maintainable frontend architecture.",
    responsibilities: [
      "Build and maintain Vue / Nuxt applications",
      "Implement reusable, accessible UI components",
      "Integrate APIs and Web3 interactions where needed",
      "Partner with design on accurate, polished UX",
      "Optimize performance and frontend reliability",
      "Participate in reviews and frontend standards",
    ],
    requirements: [
      "3+ years frontend experience with strong Vue proficiency",
      "Experience with TypeScript and modern Vue tooling",
      "Solid understanding of responsive design and state management",
      "Experience consuming REST/GraphQL APIs",
      "Comfort with Git and component-driven development",
    ],
    niceToHave: [
      "Nuxt experience",
      "Web3 / wallet UI experience",
      "Design system work",
      "React familiarity",
    ],
    techStack: ["Vue", "Nuxt", "TypeScript", "Vite", "Pinia", "TailwindCSS", "REST / GraphQL"],
  },
  {
    file: "full-stack-engineer.ts",
    order: 44,
    slug: "full-stack-engineer",
    title: "Full-Stack Engineer",
    department: "Engineering",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Full-Stack-Engineer-35803938ce42806ab052f126c0135258",
    summary: "Deliver end-to-end product features across React frontends and Node backends.",
    about:
      "We are hiring a Full-Stack Engineer to ship product features across frontend and backend. You will own delivery from API design through polished UI, working closely with product and design. This is a hands-on role for engineers who like closing the loop.",
    responsibilities: [
      "Build frontend features with React and TypeScript",
      "Design and implement backend APIs and data models",
      "Ship features end-to-end with tests and observability",
      "Collaborate with design on UX quality",
      "Integrate third-party and blockchain services when needed",
      "Improve shared components and engineering standards",
    ],
    requirements: [
      "3+ years full-stack engineering experience",
      "Strong TypeScript across React and Node.js",
      "Experience with PostgreSQL and API design",
      "Solid product sense and collaboration skills",
      "Comfort owning features from design through production",
    ],
    niceToHave: [
      "Next.js experience",
      "Web3 integrations",
      "Cloud deployment familiarity",
      "Design system contributions",
    ],
    techStack: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
  },
  {
    file: "staff-software-engineer.ts",
    order: 46,
    slug: "staff-software-engineer",
    title: "Staff Software Engineer",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Staff-Software-Engineer-37703938ce42806d862bd6d351ac1b7b",
    summary: "Set technical direction and ship high-leverage systems across products.",
    about:
      "We are hiring a Staff Software Engineer to drive architecture and delivery across critical systems. You will unblock teams, define standards, and still write production code. This is a senior IC role with broad technical influence.",
    responsibilities: [
      "Lead architecture for complex cross-team initiatives",
      "Ship high-leverage backend and platform systems",
      "Raise engineering quality through reviews and standards",
      "Mentor senior engineers and improve execution",
      "Partner with product and tech leads on roadmap tradeoffs",
      "Reduce operational risk in production systems",
    ],
    requirements: [
      "8+ years software engineering experience",
      "Proven staff-level ownership of complex systems",
      "Strong system design and communication skills",
      "Deep expertise in at least one major stack (Node/Go/Rust/Java)",
      "Track record mentoring engineers and shaping standards",
    ],
    niceToHave: [
      "Web3 / fintech systems experience",
      "Multi-product platform leadership",
      "Cloud architecture at scale",
    ],
    techStack: ["TypeScript / Go / Rust", "PostgreSQL", "Redis", "Kubernetes", "AWS / GCP"],
  },
  {
    file: "lead-developer.ts",
    order: 48,
    slug: "lead-developer",
    title: "Lead Developer",
    department: "Engineering",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Lead-Developer-35303938ce42801088bad00f7ae92d5b",
    summary: "Lead day-to-day engineering execution while remaining hands-on in the codebase.",
    about:
      "We are hiring a Lead Developer to guide delivery across engineering workstreams. You will still write code, review PRs, and keep projects moving while raising team standards. This is a hands-on leadership role.",
    responsibilities: [
      "Lead implementation across assigned product workstreams",
      "Review code and enforce engineering best practices",
      "Break down work and unblock engineers",
      "Coordinate with product, design, and QA",
      "Own technical quality of releases",
      "Mentor developers and improve delivery cadence",
    ],
    requirements: [
      "5+ years software engineering experience",
      "Prior technical leadership on shipping teams",
      "Strong coding ability in TypeScript or equivalent",
      "Excellent communication and prioritization skills",
      "Experience delivering production web or blockchain products",
    ],
    niceToHave: [
      "Agency / multi-client delivery experience",
      "Web3 product background",
      "Hiring and mentoring experience",
    ],
    techStack: ["TypeScript", "React", "Node.js", "PostgreSQL", "Docker", "AWS / GCP"],
  },
  {
    file: "tech-lead.ts",
    order: 50,
    slug: "tech-lead",
    title: "Tech Lead",
    department: "Engineering",
    team: "Platform",
    sourceUrl: "https://rwa-jd.notion.site/Tech-Lead-35303938ce4281a1a509d1fdcd9717b1",
    summary: "Lead architecture and engineering execution across backend and blockchain-integrated systems.",
    about:
      "We are hiring a Tech Lead to lead architecture, engineering execution, and technical direction across backend and blockchain-integrated systems. You will be responsible for ensuring scalable, secure, and production-ready backend systems, while guiding a team of engineers and maintaining high engineering standards. This is a hands-on leadership role (you still code).",
    responsibilities: [
      "Lead backend architecture and system design decisions",
      "Oversee development of Node.js/TypeScript backend services",
      "Guide integration with blockchain smart contracts and APIs",
      "Review code and enforce engineering best practices",
      "Design scalable APIs, services, and data models",
      "Coordinate backend development across multiple projects",
      "Work closely with blockchain engineers and frontend teams",
      "Define technical standards (testing, CI/CD, architecture patterns)",
      "Mentor engineers and improve team execution quality",
      "Participate in hiring and technical interviews",
    ],
    requirements: [
      "5+ years of backend engineering experience",
      "Strong expertise in Node.js and TypeScript",
      "Proven experience leading technical teams or projects",
      "Strong system design and architecture skills",
      "Experience with PostgreSQL, Redis, and scalable backend systems",
      "Understanding of REST APIs and/or GraphQL",
      "Experience integrating external systems (APIs, Web3, or microservices)",
      "Strong coding fundamentals and ability to review production code",
    ],
    niceToHave: [
      "Experience with blockchain or Web3 integrations (ethers.js, smart contract APIs)",
      "Experience in distributed systems or event-driven architectures",
      "Familiarity with cloud infrastructure (AWS / GCP)",
      "Experience in fintech, SaaS, or consulting environments",
      "Exposure to high-scale backend systems",
    ],
    techStack: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "ethers.js", "Docker", "Kubernetes", "AWS / GCP"],
    successLooksLike: [
      "Stable and scalable backend systems in production",
      "Clear and consistent architecture across services",
      "Reduced production issues and improved system reliability",
      "Strong engineering culture and code quality",
      "Efficient collaboration between backend and blockchain teams",
    ],
    hiringProcess: [
      "Application review",
      "Technical discussion (system design + backend architecture)",
      "Leadership interview (technical + team execution)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "GitHub profile (required)",
      "Examples of backend systems or architecture work",
    ],
  },
  {
    file: "engineering-leader.ts",
    order: 52,
    slug: "engineering-leader",
    title: "Engineering Leader",
    department: "Engineering",
    team: "Leadership",
    sourceUrl: "https://rwa-jd.notion.site/Engineering-Leader-37203938ce42803eb83bda5373e6d029",
    summary: "Lead engineering org health, delivery quality, and multi-team technical outcomes.",
    about:
      "We are hiring an Engineering Leader to oversee engineering execution across teams. You will hire, coach, and create clarity while keeping delivery quality high across product and platform work. This role balances people leadership with strong technical judgment.",
    responsibilities: [
      "Lead engineering managers and senior ICs",
      "Own delivery outcomes across multiple workstreams",
      "Set engineering standards and operational practices",
      "Partner with product and founders on roadmap tradeoffs",
      "Build hiring pipelines and strengthen team quality",
      "Improve reliability, planning, and cross-team collaboration",
    ],
    requirements: [
      "7+ years engineering experience including people leadership",
      "Track record leading multi-team software delivery",
      "Strong technical judgment across web and backend systems",
      "Excellent communication with executives and engineers",
      "Experience hiring and developing senior talent",
    ],
    niceToHave: [
      "Web3 / fintech leadership experience",
      "Agency or multi-product org experience",
      "Hands-on background in TypeScript systems",
    ],
    techStack: ["TypeScript ecosystems", "Cloud platforms", "CI/CD", "Observability"],
  },
  {
    file: "technical-architect.ts",
    order: 54,
    slug: "technical-architect",
    title: "Technical Architect",
    department: "Engineering",
    team: "Architecture",
    sourceUrl: "https://rwa-jd.notion.site/Technical-Architect-3ac03938ce4280d18502f7d4fedf7c03",
    summary: "Define system architecture across product, backend, and blockchain surfaces.",
    about:
      "We are hiring a Technical Architect to define end-to-end architecture for digital and blockchain products. You will translate product goals into scalable designs, guide implementation choices, and keep systems coherent as they grow. This is a hands-on architecture role.",
    responsibilities: [
      "Design system architecture across services and products",
      "Produce clear technical designs and ADRs",
      "Guide teams on APIs, data models, and integration patterns",
      "Evaluate build vs buy and technology tradeoffs",
      "Review implementations for scalability and security",
      "Partner with tech leads to keep architecture practical",
    ],
    requirements: [
      "7+ years engineering experience with architecture ownership",
      "Deep experience designing distributed web systems",
      "Strong API, data, and security design skills",
      "Ability to communicate architecture to technical and business stakeholders",
      "Experience guiding multiple delivery teams",
    ],
    niceToHave: [
      "Blockchain architecture experience",
      "RWA / fintech domain knowledge",
      "Cloud architecture certifications or equivalent depth",
    ],
    techStack: ["Node.js / Go / Java", "PostgreSQL", "Event systems", "Kubernetes", "AWS / GCP", "Web3 integrations"],
  },
  {
    file: "devops-engineer.ts",
    order: 56,
    slug: "devops-engineer",
    title: "DevOps Engineer",
    department: "Engineering",
    team: "Infrastructure",
    sourceUrl: "https://rwa-jd.notion.site/DevOps-Engineer-35f03938ce42801da78ed5a2184a8645",
    summary: "Own CI/CD, cloud infrastructure, and reliability for production systems.",
    about:
      "We are hiring a DevOps Engineer to build and operate cloud infrastructure, CI/CD, and reliability tooling. You will help engineering teams ship safely and keep production systems observable. This is a hands-on infrastructure role.",
    responsibilities: [
      "Design and maintain CI/CD pipelines",
      "Manage cloud infrastructure and environments",
      "Improve observability, alerting, and incident response",
      "Harden security baselines and secrets management",
      "Support containerized deployments and scaling",
      "Partner with engineers on release and reliability needs",
    ],
    requirements: [
      "3+ years DevOps / platform engineering experience",
      "Strong experience with AWS or GCP",
      "Hands-on Docker and Kubernetes experience",
      "Solid CI/CD knowledge (GitHub Actions or equivalent)",
      "Scripting proficiency (Bash, Python, or TypeScript)",
      "Understanding of networking, IAM, and monitoring",
    ],
    niceToHave: [
      "Terraform / IaC expertise",
      "Blockchain node operations",
      "Security / compliance experience",
      "SRE practices and SLO design",
    ],
    techStack: ["AWS / GCP", "Docker", "Kubernetes", "Terraform", "GitHub Actions", "Prometheus / Grafana"],
  },
  {
    file: "qa-engineer.ts",
    order: 58,
    slug: "qa-engineer",
    title: "QA Engineer",
    department: "Engineering",
    team: "Quality",
    sourceUrl: "https://rwa-jd.notion.site/QA-Engineer-37703938ce42809b9c95f27f4e60ae63",
    summary: "Raise product quality through manual, automated, and release testing.",
    about:
      "We are hiring a QA Engineer to own quality across web, mobile, and blockchain-integrated products. You will design test plans, automate critical flows, and partner with engineers before release. This is a hands-on quality role focused on risk reduction.",
    responsibilities: [
      "Create test plans and regression suites",
      "Perform functional, integration, and exploratory testing",
      "Automate high-value UI and API tests",
      "Validate wallet, transaction, and edge-case flows",
      "Track defects and verify fixes before release",
      "Improve release checklists and quality standards",
    ],
    requirements: [
      "3+ years QA experience on software products",
      "Strong test design and bug-reporting skills",
      "Experience with API testing and browser automation",
      "Comfort testing complex multi-step product flows",
      "Clear communication with engineering and product",
    ],
    niceToHave: [
      "Playwright / Cypress / Selenium experience",
      "Web3 transaction testing experience",
      "Mobile testing experience",
      "Basic scripting ability",
    ],
    techStack: ["Playwright / Cypress", "Postman / API testing", "CI pipelines", "Browser / mobile tooling"],
  },
  {
    file: "rd-engineer.ts",
    order: 60,
    slug: "rd-engineer",
    title: "R&D Engineer",
    department: "Engineering",
    team: "R&D",
    sourceUrl: "https://rwa-jd.notion.site/R-D-Engineer-35a03938ce42806293b9d4d76e4f3f58",
    summary: "Prototype emerging tech and convert promising ideas into product paths.",
    about:
      "We are hiring an R&D Engineer to explore emerging technologies and turn promising ideas into working prototypes. You will evaluate feasibility, build proofs of concept, and help product teams decide what to industrialize. This is a hands-on experimental engineering role.",
    responsibilities: [
      "Research emerging tools, protocols, and architectures",
      "Build prototypes and technical proofs of concept",
      "Evaluate feasibility, risk, and performance",
      "Document findings and recommend next steps",
      "Support productization handoff to delivery teams",
      "Stay current with Web3, AI, and platform advances",
    ],
    requirements: [
      "3+ years software engineering experience",
      "Strong prototyping skills across languages/stacks",
      "Ability to evaluate technical tradeoffs quickly",
      "Clear technical writing and demos",
      "Curiosity and comfort with ambiguity",
    ],
    niceToHave: [
      "Blockchain protocol research experience",
      "AI / ML applied engineering",
      "Prior startup or lab environment",
    ],
    techStack: ["TypeScript / Python / Rust", "Prototype tooling", "Cloud sandboxes", "Web3 SDKs"],
  },
  {
    file: "data-analyst.ts",
    order: 70,
    slug: "data-analyst",
    title: "Data Analyst",
    department: "Data",
    team: "Data",
    sourceUrl: "https://rwa-jd.notion.site/Data-Analyst-35a03938ce428042bf68ebcd441652fe",
    summary: "Turn product and on-chain data into clear insights for decisions.",
    about:
      "We are hiring a Data Analyst to analyze product, operational, and on-chain data. You will build reports, answer business questions, and help teams make better decisions. This is a hands-on analytics role with strong SQL and communication focus.",
    responsibilities: [
      "Analyze product and operational datasets",
      "Build dashboards and recurring reports",
      "Partner with product and engineering on metrics definitions",
      "Investigate anomalies and explain trends",
      "Support experiments and go-to-market analysis",
      "Document data assumptions and methodology",
    ],
    requirements: [
      "3+ years data analysis experience",
      "Strong SQL skills",
      "Experience with BI tools (Looker, Metabase, Tableau, or similar)",
      "Ability to translate data into clear recommendations",
      "Comfort working with imperfect real-world datasets",
    ],
    niceToHave: [
      "Python / R for analysis",
      "Blockchain / on-chain analytics",
      "Product analytics experience",
      "Statistics fundamentals",
    ],
    techStack: ["SQL", "Python", "BI / dashboards", "PostgreSQL", "Spreadsheet modeling"],
  },
  {
    file: "data-engineer.ts",
    order: 72,
    slug: "data-engineer",
    title: "Data Engineer",
    department: "Data",
    team: "Data",
    sourceUrl: "https://rwa-jd.notion.site/Data-Engineer-37503938ce4280b0aba7c8ae0015e284",
    summary: "Design scalable data pipelines and analytics infrastructure.",
    about:
      "We are hiring a Data Engineer to design, build, and maintain scalable data pipelines and analytics infrastructure. You will work closely with product, engineering, and business teams to ensure reliable data collection, processing, storage, and reporting across multiple products and systems. This is a hands-on engineering role focused on data architecture, ETL pipelines, and analytics infrastructure.",
    responsibilities: [
      "Design and build scalable data pipelines and ETL workflows",
      "Integrate data from multiple sources and services",
      "Develop and maintain data storage and processing systems",
      "Ensure data quality, consistency, and reliability",
      "Optimize data workflows for performance and scalability",
      "Support reporting, analytics, and business intelligence initiatives",
      "Collaborate with backend, product, and analytics teams",
      "Monitor and troubleshoot data infrastructure issues",
      "Document data models, pipelines, and architecture decisions",
    ],
    requirements: [
      "3+ years of experience in data engineering",
      "Strong SQL and database design skills",
      "Experience building ETL/ELT pipelines",
      "Experience with Python or similar scripting languages",
      "Understanding of data modeling and data warehousing concepts",
      "Experience working with large datasets and distributed systems",
      "Strong problem-solving and analytical skills",
    ],
    niceToHave: [
      "Experience with cloud platforms (AWS, GCP, Azure)",
      "Familiarity with Kafka, streaming systems, or event-driven architectures",
      "Experience with PostgreSQL, MongoDB, Redis, or data warehouses",
      "Knowledge of analytics and BI platforms",
      "Experience with blockchain or Web3 data sources",
      "Exposure to machine learning data pipelines",
    ],
    techStack: ["Python", "SQL", "PostgreSQL", "MongoDB", "Redis", "Kafka", "AWS / GCP", "ETL / ELT"],
    successLooksLike: [
      "Reliable and scalable data pipelines in production",
      "High-quality and accessible data across teams",
      "Efficient reporting and analytics infrastructure",
      "Optimized data processing and storage systems",
      "Strong collaboration between engineering and business teams",
    ],
    hiringProcess: [
      "Application review",
      "Technical screening (SQL and data engineering discussion)",
      "Practical exercise or architecture review",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "GitHub profile or project portfolio (preferred)",
      "Examples of data pipelines, platforms, or engineering projects",
    ],
  },
  {
    file: "database-architect.ts",
    order: 74,
    slug: "database-architect",
    title: "Database Architect",
    department: "Data",
    team: "Data",
    sourceUrl: "https://rwa-jd.notion.site/DataBase-Architect-36c03938ce4280b59632f1d298037876",
    summary: "Design resilient data models and database architectures for production systems.",
    about:
      "We are hiring a Database Architect to design and evolve database architecture across products. You will own modeling, performance, and operational patterns for critical data stores. This is a specialized role focused on reliability and long-term data design.",
    responsibilities: [
      "Design relational and complementary data architectures",
      "Lead schema design and migration strategies",
      "Optimize query performance and indexing",
      "Define backup, replication, and recovery standards",
      "Partner with engineers on data access patterns",
      "Document models and operational playbooks",
    ],
    requirements: [
      "5+ years database engineering / architecture experience",
      "Expert PostgreSQL (or equivalent RDBMS) skills",
      "Strong data modeling and performance tuning expertise",
      "Experience with migrations in production systems",
      "Ability to communicate tradeoffs to engineering leaders",
    ],
    niceToHave: [
      "Distributed SQL / NoSQL architecture experience",
      "Data warehouse design",
      "Fintech / high-consistency systems",
      "Cloud managed database platforms",
    ],
    techStack: ["PostgreSQL", "Redis", "MongoDB", "SQL modeling", "Migration tooling", "AWS / GCP"],
  },
  {
    file: "product-designer.ts",
    order: 80,
    slug: "product-designer",
    title: "Product Designer (UI/UX – Web3 / Digital Products)",
    department: "Design",
    team: "Design",
    sourceUrl:
      "https://rwa-jd.notion.site/Product-Designer-UI-UX-Web3-Digital-Products-35303938ce4280af91d0effea3854543",
    summary: "Design intuitive interfaces for blockchain and digital products.",
    about:
      "We are hiring a Product Designer to design intuitive, user-centered interfaces for blockchain and digital products. You will be responsible for turning complex technical systems into simple, usable, and visually clear experiences across web and mobile applications. This is a hands-on design role with strong product involvement, working closely with engineering and product teams.",
    responsibilities: [
      "Design user interfaces for web and mobile applications",
      "Create user flows, wireframes, and high-fidelity mockups",
      "Work closely with product managers and engineers to define UX requirements",
      "Simplify complex blockchain interactions into usable experiences",
      "Design onboarding flows, dashboards, and transactional interfaces",
      "Maintain and evolve design systems and UI components",
      "Conduct UX thinking around usability, clarity, and accessibility",
      "Collaborate with frontend developers during implementation",
      "Iterate designs based on user feedback and product needs",
    ],
    requirements: [
      "3+ years of experience in product or UX/UI design",
      "Strong portfolio of web or mobile product design work",
      "Experience designing complex systems or data-heavy interfaces",
      "Proficiency in Figma (or similar design tools)",
      "Strong understanding of UX principles and interaction design",
      "Ability to work closely with engineering teams",
      "Good communication and problem-solving skills",
    ],
    niceToHave: [
      "Experience in Web3 / blockchain / fintech products",
      "Understanding of wallet flows, transactions, or DeFi UX",
      "Experience designing design systems at scale",
      "Basic understanding of frontend development (HTML/CSS/React)",
      "Experience in startup or fast-paced environments",
      "Motion design or prototyping skills",
    ],
    techStack: ["Figma", "React · Next.js context", "Design systems", "Web3 wallet UX patterns"],
    successLooksLike: [
      "Clear, intuitive user experiences across all products",
      "Reduced user friction in blockchain interactions",
      "Strong, consistent design system across applications",
      "Improved usability and onboarding conversion",
      "High-quality collaboration with engineering teams",
    ],
    hiringProcess: [
      "Application review",
      "Portfolio review (critical step)",
      "Design task (UX problem-solving exercise)",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "Portfolio (required)",
      "Case studies or product design examples",
    ],
  },
  {
    file: "senior-product-designer.ts",
    order: 82,
    slug: "senior-product-designer",
    title: "Senior Product Designer",
    department: "Design",
    team: "Design",
    sourceUrl: "https://rwa-jd.notion.site/Senior-Product-Designer-38f03938ce42805ab710e65e828644fc",
    summary: "Lead product design quality across complex digital and Web3 experiences.",
    about:
      "We are hiring a Senior Product Designer to lead design quality across complex products. You will set interaction standards, mentor designers, and partner closely with product and engineering on high-stakes flows. This is a senior hands-on design role.",
    responsibilities: [
      "Lead end-to-end design for major product surfaces",
      "Own and evolve the design system",
      "Mentor designers and raise craft quality",
      "Simplify complex operational and blockchain flows",
      "Run critiques and collaborate deeply with engineering",
      "Shape UX strategy with product leadership",
    ],
    requirements: [
      "5+ years product design experience",
      "Strong portfolio of shipped complex products",
      "Expert Figma and interaction design skills",
      "Experience leading design on multi-squad products",
      "Excellent collaboration with engineering and PM partners",
    ],
    niceToHave: [
      "Web3 / fintech UX experience",
      "Design systems at scale",
      "Motion / prototyping depth",
      "Prior lead designer experience",
    ],
    techStack: ["Figma", "Design systems", "Prototyping", "Web / mobile product UX"],
    hiringProcess: [
      "Application review",
      "Portfolio review",
      "Design exercise",
      "Final discussion",
    ],
    howToApply: ["Resume or LinkedIn", "Portfolio (required)", "Case studies"],
  },
  {
    file: "product-manager.ts",
    order: 90,
    slug: "product-manager",
    title: "Product Manager",
    department: "Product",
    team: "Product",
    sourceUrl: "https://rwa-jd.notion.site/Product-Manager-35303938ce42819189f6e4c0b7dbabd3",
    summary: "Lead product planning and delivery across software development projects.",
    about:
      "We are hiring a Product Manager to lead product planning, execution, and delivery across software development projects. You will act as the bridge between clients, business stakeholders, and engineering teams, ensuring clear requirements, strong execution, and successful product delivery. This role is both strategic and execution-focused, with direct involvement in product lifecycle management.",
    responsibilities: [
      "Define product requirements based on client and business needs",
      "Translate business goals into clear technical specifications",
      "Work closely with engineering teams (backend, frontend, blockchain, QA)",
      "Manage product roadmap, scope, and delivery timelines",
      "Write user stories, acceptance criteria, and PRDs",
      "Prioritize features based on value, risk, and effort",
      "Coordinate with designers and business analysts",
      "Ensure successful product delivery across development cycles",
      "Gather feedback and iterate on product improvements",
    ],
    requirements: [
      "3+ years of experience in product management or delivery roles",
      "Experience working with software development teams",
      "Strong understanding of Agile / Scrum methodologies",
      "Ability to communicate with technical and non-technical stakeholders",
      "Experience writing product requirements and user stories",
      "Strong organizational and prioritization skills",
      "Ability to manage multiple projects simultaneously",
    ],
    niceToHave: [
      "Experience in outsourcing or agency environments",
      "Familiarity with blockchain, fintech, or enterprise software",
      "Technical background (engineering, QA, or business analysis)",
      "Experience with tools like Jira, Confluence, Notion, or Linear",
      "UX/UI understanding or experience working with design teams",
    ],
    techStack: [
      "Blockchain applications",
      "Web applications",
      "Mobile applications",
      "Backend systems (Node.js, Go, Rust)",
      "Cloud infrastructure",
    ],
    successLooksLike: [
      "Clear and well-defined product requirements",
      "On-time and high-quality project delivery",
      "Strong alignment between clients and engineering teams",
      "Reduced ambiguity and improved execution efficiency",
      "Successful feature releases and product iterations",
    ],
    hiringProcess: [
      "Application review",
      "Product thinking interview (case discussion)",
      "Technical collaboration / scenario exercise",
      "Final discussion",
    ],
    howToApply: [
      "Resume or LinkedIn",
      "Examples of products or projects managed",
      "Brief description of delivery challenges handled",
    ],
  },
  {
    file: "project-manager.ts",
    order: 92,
    slug: "project-manager",
    title: "Project Manager",
    department: "Operations",
    team: "Delivery",
    sourceUrl: "https://rwa-jd.notion.site/Project-Manager-35303938ce42816897f0e40abbeabc67",
    summary: "Drive timelines, communication, and delivery across engineering projects.",
    about:
      "We are hiring a Project Manager to coordinate delivery across software projects. You will keep scope, timeline, and communication clear between clients and engineering teams. This is an execution-focused role that keeps complex work moving.",
    responsibilities: [
      "Plan and track project timelines, milestones, and risks",
      "Coordinate engineering, design, QA, and stakeholders",
      "Maintain clear status reporting and escalation paths",
      "Manage scope changes and delivery tradeoffs",
      "Facilitate ceremonies and keep teams unblocked",
      "Improve delivery process and documentation",
    ],
    requirements: [
      "3+ years project management experience in software delivery",
      "Strong Agile / Scrum facilitation skills",
      "Excellent written and verbal communication",
      "Ability to manage multiple concurrent workstreams",
      "Comfort working with technical teams and clients",
    ],
    niceToHave: [
      "Agency / outsourcing delivery experience",
      "Blockchain or fintech project background",
      "PMP / Scrum certification",
      "Technical background",
    ],
    techStack: ["Jira / Linear", "Notion / Confluence", "Agile delivery tooling"],
  },
  {
    file: "developer-relations-engineer.ts",
    order: 94,
    slug: "developer-relations-engineer",
    title: "Developer Relations Engineer",
    department: "Operations",
    team: "Growth",
    sourceUrl:
      "https://rwa-jd.notion.site/Developer-Relations-Engineer-35303938ce4281449c28dd0c7d617f56",
    summary: "Grow developer adoption through docs, demos, and community technical support.",
    about:
      "We are hiring a Developer Relations Engineer to help developers understand and integrate our products. You will create technical content, demos, and community support while feeding product insights back to engineering. This is a technical, outward-facing role.",
    responsibilities: [
      "Create technical docs, tutorials, and sample apps",
      "Support developers in community channels",
      "Present demos, workshops, and technical talks",
      "Gather feedback and relay insights to product/engineering",
      "Improve onboarding and integration experience",
      "Build relationships with ecosystem partners",
    ],
    requirements: [
      "3+ years engineering or developer advocacy experience",
      "Strong writing and public technical communication",
      "Hands-on coding ability (TypeScript / JS preferred)",
      "Experience explaining complex systems simply",
      "Comfort engaging with developer communities",
    ],
    niceToHave: [
      "Web3 / blockchain developer community experience",
      "Prior DevRel or technical content role",
      "Conference speaking experience",
      "Open-source contributions",
    ],
    techStack: ["TypeScript", "Docs tooling", "Sample apps", "Web3 SDKs"],
    howToApply: [
      "Resume or LinkedIn",
      "Writing samples or talks (required)",
      "GitHub profile",
    ],
  },
  {
    file: "customer-support-community-manager.ts",
    order: 96,
    slug: "customer-support-community-manager",
    title: "Customer Support / Community Manager",
    department: "Operations",
    team: "Growth",
    sourceUrl:
      "https://rwa-jd.notion.so/Customer-Support-Community-Manager-2f803938ce428059a6e1ee7c36663a2d",
    summary: "Support users and grow an engaged product community.",
    about:
      "We are hiring a Customer Support / Community Manager to help users succeed and keep community channels healthy. You will handle support, create helpful content, and represent the product voice across Discord, Telegram, and email. This is a customer-facing operations role.",
    responsibilities: [
      "Respond to user support requests with clarity and speed",
      "Moderate and grow community channels",
      "Create FAQs, help articles, and onboarding guides",
      "Escalate product issues and track recurring themes",
      "Coordinate with product and engineering on user pain points",
      "Support launches, AMAs, and community programs",
    ],
    requirements: [
      "2+ years customer support or community management experience",
      "Excellent written communication",
      "Comfort with Discord / Telegram / social community tooling",
      "Strong empathy and problem-solving under pressure",
      "Ability to learn technical product details quickly",
    ],
    niceToHave: [
      "Web3 / crypto community experience",
      "Support tooling experience (Zendesk, Intercom, etc.)",
      "Content creation skills",
      "Multilingual communication",
    ],
    techStack: ["Discord / Telegram", "Helpdesk tooling", "Docs / knowledge base"],
    howToApply: [
      "Resume or LinkedIn",
      "Examples of community or support work",
      "Short note on how you handle difficult user issues",
    ],
  },
];

const obsolete = [
  "business-analyst.ts",
  "product-engineer.ts",
  "senior-ai-engineer.ts",
  "security-engineer.ts",
  "blockchain-engineer.ts",
];

function esc(str) {
  return String(str).replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function arr(items) {
  return `[\n${items.map((i) => `    "${esc(i)}"`).join(",\n")},\n  ]`;
}

function render(job) {
  const optional = [];
  if (job.stage) optional.push(`  stage: "${esc(job.stage)}",`);
  if (job.techStack) optional.push(`  techStack: ${arr(job.techStack)},`);
  if (job.successLooksLike) optional.push(`  successLooksLike: ${arr(job.successLooksLike)},`);
  if (job.hiringProcess) optional.push(`  hiringProcess: ${arr(job.hiringProcess)},`);
  if (job.howToApply) optional.push(`  howToApply: ${arr(job.howToApply)},`);
  if (job.benefits) optional.push(`  benefits: ${arr(job.benefits)},`);
  if (job.sourceUrl) optional.push(`  sourceUrl: "${esc(job.sourceUrl)}",`);

  return `import { defineJob } from "../shared";

export default defineJob({
  open: true,
  order: ${job.order},
  slug: "${job.slug}",
  title: "${esc(job.title)}",
  department: "${job.department}",
  team: "${esc(job.team)}",
  location: "${LOC}",
  type: "${TYPE}",
${optional.join("\n")}
  summary: "${esc(job.summary)}",
  about: "${esc(job.about)}",
  responsibilities: ${arr(job.responsibilities)},
  requirements: ${arr(job.requirements)},
  niceToHave: ${arr(job.niceToHave)},
});
`;
}

fs.mkdirSync(rolesDir, { recursive: true });

for (const name of obsolete) {
  const p = path.join(rolesDir, name);
  if (fs.existsSync(p)) {
    fs.unlinkSync(p);
    console.log("deleted", name);
  }
}

for (const job of jobs) {
  const p = path.join(rolesDir, job.file);
  fs.writeFileSync(p, render(job), "utf8");
  console.log("wrote", job.file);
}

console.log(`\nDone: ${jobs.length} roles`);
